### ISSUE TITLE
Can we build tensorflow graph using UE4 blueprint?

### ISSUE THREAD

**Issue by tcmxx** [getnamo/tensorflow-ue4#9]
Hello, 
I am still building graphs with Tensorflow and haven't tried tensorflowue4 a lot yet. However, I am wondering is it possible to make changes to the plugin so that I can build tensorflow nn graphs using the blueprint of unreal? 
I guess It will be possible if I can call any python functions, with some input parameters modifiable in blueprint,  and feed the output of that python function, for example, a tensorflow operation, to another python function as input.

Thanks!

**Comment by getnamo** [comment]
The concept of building graphs in blueprints is one of the features I had in mind for the near future evolution of the plugin. You can start building bindings now, since there is a custom function api which allows you to call any function on your script.

In 0.2.0 api (https://github.com/getnamo/tensorflow-ue4/commit/605775f48d20c581d17d443b09b8115d74cd630a#diff-01eaadb8038998e05cbd7d7709697bebR100) a ```CallCustomFunction``` was added to the Tensorflow Component that allows you to call any python function on your python script with string arg and string return expected. If you're using JSON encoding for your strings that means you can specify any type of parameters and get any type of return object conveniently.

You'll find a small documentation section for that function here: https://github.com/getnamo/tensorflow-ue4#custom-functions

Note that any function calls using this custom function api will be synchronous, so don't do any operations that take a long time there unless you thread it manually. Despite that, defining nn graphs is generally a low cost operation and it should work well, though compiling the graph may need threading.

**Comment by tcmxx** [comment]
hello,

Thank you very much for reply! string arg/return is good enough now. I might want to make use of this for my Master's thesis and I think it i will be really handy.

Hope it will keep evolving  in the future~
